---
title: "qPCR data analysis using R"
format:
  html:
    df-print: paged
---

-   https://cran.r-project.org/web/packages/pcr/vignettes/qpcr_analysis.html
-   https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-7-85
-   https://www.sigmaaldrich.com/US/en/technical-documents/technical-article/genomics/qpcr/data-analysis
-   https://bitesizebio.com/24894/4-easy-steps-to-analyze-your-qpcr-data-using-double-delta-ct-analysis/
-   https://www.nature.com/articles/nprot.2008.73
-   http://satqpcr.sophia.inra.fr/
-   https://academic.oup.com/clinchem/article/55/4/611/5631762
-   https://www.researchgate.net/post/when_performing_a\_stastical_analysis_on_qPCR_data_where_do_you_apply_ANOVA_or_TTest_on_dct_values_or_fold_change
-   https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1949-5

```{r}
#| output: false
library(tidyverse)
library(magrittr)
library(janitor)
library(readxl)
library(broom.mixed)
library(pcr)
library(lme4)
library(lmerTest)
library(DHARMa)
library(effectsize)
library(marginaleffects)
```

```{r}
# default mode delta_delta_ct
## locate and read raw ct data
ct1 <- read.csv(system.file('extdata', 'ct1.csv', package = 'pcr'))

## add grouping variable
group_var <- rep(c('brain', 'kidney'), each = 6)

# calculate all values and errors in one step
## mode == 'separate_tube' default
pcr_analyze(ct1,
  group_var = group_var,
  reference_gene = 'GAPDH',
  reference_group = 'brain')

# run stat tests
pcr_test(ct1, 
         group_var = group_var,
         reference_gene = 'GAPDH',
         reference_group = 'brain',
         test = "t.test")

pcr_test(ct1, 
         group_var = group_var,
         reference_gene = 'GAPDH',
         reference_group = 'brain',
         test = "wilcox.test")

pcr_test(ct1, 
         group_var = group_var,
         reference_gene = 'GAPDH',
         reference_group = 'brain',
         test = "lm")
```

```{r}
# default mode delta_delta_ct
## locate and read raw ct data
ct2 = read.csv(system.file('extdata', 'ct2.csv', package = 'pcr'))

## add grouping variable
group_var = rep(c('brain', 'kidney'), each = 6)

# calculate all values and errors in one step
## mode == 'same_tube'
pcr_analyze(ct2,
  group_var = group_var,
  reference_gene = 'GAPDH',
  reference_group = 'brain',
  mode = 'same_tube')

# run stat tests
pcr_test(ct2, 
         group_var = group_var,
         reference_gene = 'GAPDH',
         reference_group = 'brain',
         test = "t.test")

pcr_test(ct2, 
         group_var = group_var,
         reference_gene = 'GAPDH',
         reference_group = 'brain',
         test = "wilcox.test")

pcr_test(ct2, 
         group_var = group_var,
         reference_gene = 'GAPDH',
         reference_group = 'brain',
         test = "lm")
```

```{r}
# locate and read data
ct4 = read.csv(system.file('extdata', 'ct4.csv', package = 'pcr'))

# make group variable
group_var = rep(c('control', 'treatment'), each = 12)

# analyze the testing data
pcr_analyze(ct4, 
            group_var = group_var,
            reference_gene = 'ref',
            reference_group = 'control')

# run stat tests
pcr_test(ct4, 
         group_var = group_var,
         reference_gene = 'ref',
         reference_group = 'control',
         test = "t.test")

pcr_test(ct4, 
         group_var = group_var,
         reference_gene = 'ref',
         reference_group = 'control',
         test = "wilcox.test")

pcr_test(ct4, 
         group_var = group_var,
         reference_gene = 'ref',
         reference_group = 'control',
         test = "lm")
```

```{r}
df = ct4 %>% mutate(group = group_var)

df

df %>%
  group_by(group) %>%
  summarize(target.mean = mean(target),
            target.sd = sd(target),
            ref.mean = mean(ref),
            ref.sd = sd(ref),
            dct.mean = target.mean - ref.mean,
            dct.sd = sqrt(target.sd^2 + ref.sd^2))
```

```{r}
df %<>% mutate(dct = target - ref, exp = fct_relevel(group, "control"))

fit = lm(dct ~ exp, data = df)

summary(fit) %>% tidy
```

```{r}
avg_comparisons(fit, df =  insight::get_df(fit)) %>% tidy
```
